name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
  
      - name: Decode api.properties
        env:
          API_KEY: ${{ secrets.API_KEI }}
        run: echo $API_KEY > .api.properties

      - name: Decode maps.properties
        env:
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEI }}
        run: echo $MAPS_API_KEY > .maps.properties
        
      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
