name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17-${{ matrix.runs-on }}
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Decode maps.properties
        env:
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
        run: echo $MAPS_API_KEY > ./app/maps.properties
  
      - name: Decode api.properties
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: echo $API_KEY > ./app/api.properties

        

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: app/build/outputs/apk/debug/app-debug.apk
          pattern: Set up JDK 17-*
          merge-multiple: true
          overwrite: true
